### PR TITLE
Rfc7854 compliance and bug fixes

### PR DESCRIPTION
**Pull request by ruissalo**
This PR contains the following changes:

1_ Adds support for route mirroring messages, basically using the same existing logic for route monitoring messages. 
2_ Adds new peer types and statistics type to make the implementation RFC 7854 compliant.

3-Fixes two bugs related to initiation/termination messages and the use of 4 Bytes ASNs in the path attributes.

### CODE REVIEW

**Comment by xiaopeng163** [comment]
hi @ruissalo thanks for the PR. I will test this asap in my lab.

There are two issues:
- Please add `.DS_Store` to gitignore file
- We don't want to include auto-generated files to the source code, for example `AUTHORS ` and `Changelog`

thanks again!

**Comment by ruissalo** [comment]
Hi @xiaopeng163  done! not sure how I missed those 👍

**Comment by xiaopeng163** [comment]
and `yabmp/.DS_Store` 😺

**Comment by ruissalo** [comment]
fixed! :)

**Pull request merged**
